version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: contenedor-bd
    environment:
      MYSQL_ROOT_PASSWORD: Admin2024
      MYSQL_DATABASE: project_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - redProyecto
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  springboot-app:
    build:
      context: ./backendProject/alm14
      dockerfile: Dockerfile
    container_name: contenedor-Backend
    ports:
      - "9090:9090"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/project_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Admin2024
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    networks:
      - redProyecto

  frontend:
    build:
      context: ./frontendProject/frontalm14
      dockerfile: Dockerfile
    container_name: contenedor-Frontend
    ports:
      - "5545:80"
    depends_on:
      - springboot-app
    networks:
      - redProyecto

volumes:
  mysql-data:

networks:
  redProyecto:
    driver: bridge

